// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn-sD9X9gVam0_LlKcMX3M9thQqlSenlk',
    appId: '1:565119861521:web:a1ff4fe0c54e2bb64002b0',
    messagingSenderId: '565119861521',
    projectId: 'test-task-aad45',
    authDomain: 'test-task-aad45.firebaseapp.com',
    storageBucket: 'test-task-aad45.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQOg7o6DLY6rm-G7U43To-hnf17QRCMkM',
    appId: '1:565119861521:android:4b501542d892d8dc4002b0',
    messagingSenderId: '565119861521',
    projectId: 'test-task-aad45',
    storageBucket: 'test-task-aad45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9NUUCdvF_Wx9S8cP0Wg_Huf0O_f4diJ4',
    appId: '1:565119861521:ios:761ce93bad216d814002b0',
    messagingSenderId: '565119861521',
    projectId: 'test-task-aad45',
    storageBucket: 'test-task-aad45.appspot.com',
    iosBundleId: 'com.example.heyflutterTestTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9NUUCdvF_Wx9S8cP0Wg_Huf0O_f4diJ4',
    appId: '1:565119861521:ios:d6ed73a32215ce204002b0',
    messagingSenderId: '565119861521',
    projectId: 'test-task-aad45',
    storageBucket: 'test-task-aad45.appspot.com',
    iosBundleId: 'com.example.heyflutterTestTask.RunnerTests',
  );
}
